apiVersion: batch/v1
kind: CronJob
metadata:
  name: backend-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backend-cron
              image: joaofmds/python-cron:latest
              command: ["sh", "-c", "python -m src.cron"]
              envFrom:
                - configMapRef:
                    name: backend-config
                - secretRef:
                    name: backend-secret
              volumeMounts:
                - name: uploads
                  mountPath: /app/uploads
          volumes:
            - name: uploads
              persistentVolumeClaim:
                claimName: backend-uploads-pvc
          restartPolicy: OnFailure
