apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
# stringData:
#   # Replace the following with secure values:
#   # DATABASE_USER: "<secure-username>"
#   # DATABASE_PASS: "<secure-password>"
