services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - database

  backend-cron:
    build:
      context: ./backend
      dockerfile: cron.Dockerfile
    environment:
      UPLOAD_DIR: /app/uploads
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - backend

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: ${VUE_APP_API_URL}
    ports:
      - "8080:80"

volumes:
  db-data:
